version: '3.8'

services:
  app:
    build:
      context: .                # Set the build context to the root directory
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - .env                    # Load environment variables from .env file

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
